version: 2.0
jobs:
  build:
    docker:
    steps:
      - checkout
      - run:
          command: date
      - save_cache:
          key: v1-preventdata-testtest
          paths:
            - /preventData
      - restore_cache:
          key: v1-preventdata-testtest

