version: 2
jobs:
  test-A:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    - image: circleci/postgres:9.6.3-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: circle_test
    steps:
    - checkout
    - run: echo "Hello CircleCI!"
    - run:
        name: Wait for DB
        command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

  test-B:
    docker:
    - image: circleci/openjdk:10-jdk-browsers
    - image: circleci/postgres:9.6.3-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: circle_test
    steps:
    - checkout
    - run: echo "Hello CircleCI!"
    - run:
        name: Wait for DB
        command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

  test-C:
    docker:
    - image: circleci/openjdk:11-jdk-browsers
    - image: circleci/postgres:9.6.3-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: circle_test
    steps:
    - checkout
    - run: echo "Hello CircleCI!"
    - run:
        name: Wait for DB
        command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

workflows:
  version: 2
  build:
    jobs:
      - "test-A"
      - "test-B":
          requires:
            - test-A
      - "test-C":
          requires:
            - test-A

